name: anand_shop_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  #UI
  flutter_screenutil: ^5.5.3+2
  iconsax: ^0.0.8
  glassmorphism: ^3.0.0

  #LOCAL STORE
  shared_preferences: ^2.0.15

  #RIVERPOD
  flutter_riverpod: ^1.0.4

  #IMAGES
  cached_network_image: ^3.2.1
  carousel_slider: ^4.1.1

  #FIREBASE
  firebase_storage: ^10.3.4
  firebase_core: ^1.20.0
  cloud_firestore: ^3.4.3
  firebase_auth: ^3.6.2

  #FONTS
  google_fonts: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^2.0.0


flutter:

 
  uses-material-design: true
  
  assets:
    - assets/


